// Canonical planning revision. Task state and comments remain in Firebase under stable ids.
const t=(id,prio,text,meta={})=>({id,prio,text,planStatus:'offen',...meta});
const c=(title,tasks)=>({title,tasks});
const p=(id,title,subtitle,categories,timeline=[])=>({id,label:id==='phase8'?'29. Mai 2027':id.replace('phase','Phase '),title,subtitle,categories:[...categories,c('➕ Freie Zusatzaufgaben',[])],timeline});
export const projectMilestones=[['milestone_site_exposed','31.10.2026','Gelände freigelegt'],['plan2_lageplan_final','28.02.2027','Layout Freeze'],['milestone_concept_freeze','31.03.2027','Konzept Freeze'],['milestone_production_complete','09.05.2027','Production Complete'],['milestone_site_ready','23.05.2027','Site Ready'],['milestone_build_complete','28.05.2027','Build Complete']].map(([id,date,title])=>({id,date,title}));
export const EVENT_PHASES=[
p('phase1','Bestand & Richtung','September 2026',[
 c('🔴 MUSS · Kernplanung',[t('plan2_budgetrahmen','prio-1','5.000 EUR als Obergrenze, nicht als Ausgabenziel, festhalten'),t('plan2_budgetstruktur','prio-1','Budget in bereits ausgegeben, geplant, Reserve und Prognose gliedern'),t('now_dixie_zustand','prio-1','Vorhandenes Dixi für Arbeitseinsätze prüfen; nicht als finale Event-Sanitärlösung voraussetzen'),t('plan2_wetterschutz_inventur','prio-1','Baldachin, Pavillon, drei Kühlboxen, 14-Liter-Kessel, Schwenkgrill, acht LED-Laternen, Bretter, Werkzeuge, Kanister sowie Strom- und Kabelbestand inventarisieren',{area:'Inventur',due:'2026-10-31',dependencies:[],note:'Vorhandene Stückzahlen, Zustand und konkrete Fehlmengen dokumentieren.'})]),
 c('🟠 SOLL · Deko',[t('deko_sep_bestand','prio-2','Deko-, Licht- und Schilderbestand einschließlich vorhandener Stoffe, Juteschnüre sowie Materialien für Wimpelketten und Banner dokumentieren',{area:'Deko',due:'2026-10-31',budgetKey:'banner_wimpel',dependencies:['plan2_wetterschutz_inventur'],note:'Fehlmengen erst nach der Bestandsaufnahme kaufen.'}),t('deko_sep_prototyp','prio-2','Höchstens eine Musterkombination aus Banner, Wimpel und Stoff testen; keine Großproduktion')])
]),
p('phase2','Gelände freilegen','Oktober 2026',[
 c('🔴 MUSS · Ergebnis',[t('milestone_site_exposed','prio-1','MEILENSTEIN · Gelände freigelegt: Hauptfläche begehbar, zentrale Flächen und Wege offen, Vermessung und Fotos möglich'),t('now_baldachin_lager_transport','prio-1','Transport und trockene Lagerung des bereits gekauften Baldachins klären')])
]),
p('phase3','Auswerten & planen','November 2026 – Januar 2027',[
 c('🔴 MUSS · Grundlayout',[t('layout_basisversorgung','prio-1','Wetterschutz, Sitzplätze, Küche, Sanitär, Hauptwege und Transportflächen im Lageplan anordnen'),t('sanitary_requirements','prio-1','Anforderungen und Anschlüsse der endgültigen Sanitärlösung festhalten')]),
 c('🟠 SOLL · Gestaltung',[t('deko_winter_layout','prio-2','Eingang, Tor, Banner, Wimpel, Licht, Ritual-, Haupt- und Wettkampfbereiche am realen Gelände planen'),t('entrance_measure','prio-2','Eingang nach Freischnitt vermessen und fotografieren; Gestaltung danach festlegen'),t('ritual_location','prio-2','Ritualstandort nur nachrangig im Lageplan bestimmen')]),
 c('🟠 SOLL · Hybrid-LARP',[t('larp_rules_freeze','prio-2','Regeln für 30 Schicksalskarten, Sidequests, Hauptquest, Silberlinge, Questmeister und Auktion einfrieren; keine Kernmechanik ergänzen'),t('larp_design_freeze','prio-2','Karten- und Questzettel-Layout finalisieren')])
]),
p('phase4','Layout Freeze & Beschaffung','Februar – März 2027',[
 c('🔴 MUSS · Infrastruktur',[t('plan2_lageplan_final','prio-1','MEILENSTEIN · Layout bis 28.02. für Wetterschutz, Sitzplätze, Küche, Sanitär, Eingang, Wettkämpfe, Quest, Ritual und Wege festlegen'),t('feb_strombedarf','prio-1','Strombedarf, Beleuchtung, Kabel und sichere Kabelwege bestimmen'),t('seating_commit','prio-1','Bierzeltgarnituren beziehungsweise ausreichende Sitzplätze verbindlich organisieren'),t('plan2_helferrollen','prio-1','Rollen vergeben: Aufbau, Küche, Getränke, Wettkampf, Abbau, Logistik, Questmeister, Herold, Abendtechnik und optional Ritualleitung')]),
 c('🔴 MUSS · Versorgung',[t('plan2_essenskonzept','prio-1','Finales Speise- und Getränkekonzept einschließlich Trinkwasser und Kühlung festhalten'),t('kitchen_core_plan','prio-1','Kochstellen, Grill, Kessel/Topf, Arbeitsflächen, Geschirr und Serviermaterial planen')]),
 c('🟠 SOLL · Produktionsstart',[t('deko_material_plan','prio-2','Nach finalem Geländeplan Mengen für Stoff, Holz/Pfosten und Befestigung sowie Produktionsliste bestimmen'),t('entrance_design','prio-2','Torbauweise, Verankerung und modulare Transportkonstruktion planen'),t('larp_production','prio-2','Schicksalskarten, Sidequests, Silberlinge und notwendige Questobjekte produzieren'),t('music_scope','prio-2','Tatsächlich genutzte Liveinstrumente festlegen; zusätzliche Instrumente bleiben optional')]),
 c('🔴 MUSS · Freeze',[t('milestone_concept_freeze','prio-1','MEILENSTEIN · Konzept Freeze 31.03.: keine neuen großen Attraktionen, Mechaniken oder Bauprojekte')]),
 c('🟢 BONUS',[t('clay_oven_go_no_go','prio-3','Anfang April Lehmofen nur bei Zeit, Helfern, Material und Trocknungswetter freigeben; sonst streichen')])
]),
p('phase5','Produzieren & testen','April 2027',[
 c('🔴 MUSS · Infrastruktur',[t('apr_planen_testaufbau','prio-1','Baldachin und Pavillon vollständig probeaufbauen, abspannen und prüfen'),t('apr_transportprobe','prio-1','Transport, Packlogik und Aufbaufolge testen'),t('waste_transport_plan','prio-1','Müllentsorgung, Fahrzeuge, Materialtransport sowie Auf- und Abbauhelfer planen')]),
 c('🔴 MUSS · Versorgung',[t('apr_mengenplanung','prio-1','Mengen und Kosten für Eintopf, Grillergänzung, Buffet, Getränke und Trinkwasser abschließend prüfen',{area:'Budget & Versorgung',due:'2027-04-24',budgetKey:'essen_gesamt',dependencies:['finalize_stew_recipe','finalize_grill_supplement','finalize_drink_amounts'],note:'Kernbudget gegen die 5.000-EUR-Obergrenze prüfen; Spenden nicht als sichere Entlastung rechnen.'}),t('apr_kuecheninventur','prio-1','Kühlung, Kochstellen, Grill, Kessel, Arbeitsflächen, Geschirr, vorhandene Bretter, Schüsseln, Küchenhelfer und Grillwerkzeug prüfen und Fehlteile ergänzen',{area:'Küche & Geschirr',due:'2027-03-29',budgetKey:'grillwerkzeug',dependencies:['plan2_wetterschutz_inventur'],note:'Vorhandene Akazienbretter berücksichtigen; nur fehlende Teile beschaffen.'}),t('plan2_prep_zeitplan','prio-1','Vorbereitungsplan für Vortag und Eventtag erstellen')]),
 c('🟠 SOLL · Produktion & Test',[t('entrance_build','prio-2','Modulares Tor bis Ende April bauen und probeaufbauen'),t('deko_april_production','prio-2','Wimpelketten, Banner, Beschilderung und nötige Deko montagefertig herstellen und nach Zone verpacken',{area:'Deko',due:'2027-04-24',budgetKey:'banner_wimpel',dependencies:['deko_sep_bestand','plan2_lageplan_final'],note:'Beschilderung besitzt einen getrennten Budgetposten; vorhandenes Material zuerst verwenden.'}),t('larp_full_test','prio-2','LARP mit mehreren Personen testen: Hauptquest, Questökonomie und problematische Aufgaben überarbeiten'),t('event_dramaturgy','prio-2','Dramaturgie aus Wettkämpfen, Karten, Quests, Essen, Siegerehrung, Ritual/Auktion und Abendprogramm zusammenführen'),t('music_tech_test','prio-2','PA, funktionale Beleuchtung, zusätzliche warme LED-/Fackeloptik und acht vorhandene LED-Laternen testen',{area:'Technik & Beleuchtung',due:'2027-04-24',budgetKey:'beleuchtung',dependencies:['feb_strombedarf','plan2_lageplan_final'],note:'Sicherheits- und Arbeitslicht getrennt von der atmosphärischen Beleuchtung prüfen.'})]),
 c('🟢 BONUS · Ritual & Effekte',[t('ritual_project','prio-3','Ritualplatz: Standort, drei Monolithen und Altar festlegen, Materialtest machen, bauen und Stand-/Wetterfestigkeit prüfen'),t('fog_test','prio-3','Nebelmaschine nur bei sicherer, tatsächlich geplanter Nutzung testen')])
]),
p('phase6','Production Complete & Site Ready','1.–23. Mai 2027',[
 c('🔴 MUSS · Abschluss',[t('milestone_production_complete','prio-1','MEILENSTEIN · Production Complete ca. 09.05.: Eigenbauten und LARP-Material montagefertig'),t('plan2_finale_einkaufsliste','prio-1','Finale Liste für Essen, Getränke, Verbrauchsmaterial und Kerninfrastruktur'),t('may_material_packen','prio-1','Material nach Stationen packen, beschriften, Fahrzeugen zuordnen und einen Belade- sowie Rückgabeplan erstellen',{area:'Packliste & Logistik',due:'2027-05-23',budgetKey:'oa_transport',dependencies:['plan2_wetterschutz_inventur','apr_transportprobe','grounds_transport'],note:'Sperriges, zerbrechliches und gemietetes Material getrennt sichern; Rückgabekisten kennzeichnen.',planStatus:'geplant'})]),
 c('🔴 MUSS · Gelände',[t('plan2_rampe_sichern','prio-1','Stolperstellen und größere Gefahren beseitigen; Wege und Rampe sichern'),t('milestone_site_ready','prio-1','MEILENSTEIN · Site Ready ca. 23.05.: Schnitt, Wege, Flächen und Sicherheitskontrolle fertig')]),
 c('🔴 MUSS · Versorgung',[t('may_helfer_bestaetigen','prio-1','Kernrollen und Ankunftszeiten bestätigen; eine Person darf mehrere Rollen übernehmen'),t('plan2_lebensmittel_einkauf','prio-1','Haltbare Lebensmittel und Gewürze früh, frische Lebensmittel und Obst in der letzten Woche einkaufen und die Kühlkette sichern',{area:'Essen',due:'2027-05-26',budgetKey:'essen_gesamt',dependencies:['apr_mengenplanung'],note:'Eintopf, Ankommensbuffet und Grillergänzung gemeinsam nach der finalen Mengenplanung beschaffen.'}),t('plan2_getraenke_einkauf','prio-1','Bier, Wein, abgefülltes Trinkwasser und alkoholfreie Getränke beschaffen',{area:'Getränke',due:'2027-05-26',budgetKey:'getraenke_gesamt',dependencies:['apr_mengenplanung'],note:'Quellwasser bleibt Reinigung und Handhygiene vorbehalten, solange keine Trinkwasserprüfung vorliegt; Vorkühlen ist ein eigener Folgeschritt.'}),t('sanitary_delivery_check','prio-1','Toilettenwagen-Lieferung, Abholung, Standort, Zufahrt, Licht, Verbrauchsmaterial und Handwaschen bestätigen',{area:'Toilette',due:'2027-05-26',budgetKey:'grounds_sanitary',dependencies:['reserve_toilet_trailer','plan2_lageplan_final'],note:'Notwendige Sanitärlösung; Standort und Lieferfenster abschließend mit dem Anbieter bestätigen.'})]),
 c('🟠 SOLL · Programm packen',[t('larp_event_pack','prio-2','Questmeister-Unterlagen, Questbrett, Regeln, Hauptquest, Auktionspreise und Kartenwahl fertigstellen und packen'),t('music_pack','prio-2','Technik packen, Kabel/Strom zuordnen und verantwortliche Person benennen'),t('ritual_pack','prio-3','Ritualelemente nur falls umgesetzt transportfest verpacken')])
]),
p('phase7','Aufbau – keine Produktion','27.–28. Mai 2027',[
 c('🔴 MUSS · Donnerstag 27.05. Schweraufbau',[t('plan2_wetterschutz_aufbauen','prio-1','Baldachin und Pavillon aufstellen, abspannen und Sitzplätze einrichten'),t('heavy_build_logistics','prio-1','Garnituren, Mietmaterial, Küche, Tor und große Konstruktionen aufbauen'),t('plan2_strom_verlegen','prio-1','Grundstrom verlegen und Kabelwege sichern'),t('plan2_kueche_aufbauen','prio-1','Küche mit Kühlung, Kochstellen, Grill, Kessel, Flächen und Wasser aufbauen')]),
 c('🔴 MUSS · Freitag 28.05. Feinaufbau',[t('plan2_sicherheitscheck_aufbau','prio-1','Sanitär, Wege, Kabel, Licht, Erste Hilfe und Löschmittel final prüfen'),t('milestone_build_complete','prio-1','MEILENSTEIN · Build Complete 28.05.: alles steht; Eventtag ohne Bauarbeiten')]),
 c('🟠 SOLL · Freitag Atmosphäre',[t('entrance_event_build','prio-2','Vorgefertigtes Tor am 27./28. Mai aufbauen und verankern'),t('plan2_deko_aufhaengen','prio-2','Vorgefertigte Banner, Wimpel, Schilder, Licht und Deko montieren'),t('quest_area_build','prio-2','Questbereich mit fertig gepacktem Material aufbauen'),t('ritual_event_build','prio-3','Ritualplatz nur falls fertig vor Ort montieren'),t('music_event_build','prio-2','Abendtechnik aufstellen und prüfen')]),
 c('🔴 MUSS · Küche Vorabend',[t('plan2_grill_marinieren','prio-1','Lebensmittel vorbereiten, portionieren und kühlen'),t('plan2_kessel_vorbereiten','prio-1','Kesselgericht und zeitkritische Küchenarbeiten vorbereiten')])
]),
p('phase8','Eventtag & Abbau','Nur Versorgung, Restpunkte und Veranstaltung',[
 c('🔴 MUSS · Eventtag',[t('event_no_build','prio-1','Keine Banner, Monolithen oder Tore bauen; nur Versorgung, Küchenarbeiten und kleine Restpunkte'),t('plan2_event_strom','prio-1','Strom, Kabelwege und Licht funktionieren'),t('plan2_trinkwasser','prio-1','Trinkwasser sichtbar bereitstellen'),t('plan2_event_dixie','prio-1','Finale Sanitärlösung ist erreichbar, beleuchtet, ausgestattet und hat Handwaschen'),t('plan2_event_erstehilfe','prio-1','Erste Hilfe und Verantwortung sind geklärt'),t('plan2_event_loeschmittel','prio-1','Löschmittel stehen an Feuer- und Kochstellen'),t('plan2_event_aufsicht','prio-1','Waffenwettkämpfe nur nüchtern, beaufsichtigt und abgesichert')]),
 c('🟠 SOLL · Programm',[t('plan2_event_punkteliste','prio-2','Wettkampfwertung und Moderation durchführen'),t('plan2_event_musik','prio-2','Musik und Abendatmosphäre betreuen'),t('larp_event_run','prio-2','Karten, Sidequests, Hauptquest, Silberlinge und Auktion mit Questmeister durchführen')]),
 c('🔴 MUSS · Abbau',[t('plan2_abbau_muell','prio-1','Müll vollständig entfernen'),t('plan2_abbau_material','prio-1','Wetterschutz, Möbel, Küche, Technik und Material trocken verstauen'),t('plan2_abbau_endkontrolle','prio-1','Gelände auf Heringe, Kabel, Werkzeuge, Gefahren und Müll kontrollieren')])
],[['12:00','Ankunft'],['14:00–16:00','Wettkämpfe'],['16:00–17:30','Essen'],['17:30–19:00','Weitere Wettbewerbe und Questfinale'],['19:00–20:00','Siegerehrung, Ritual/Auktion'],['ab 20:00','Tavernenabend']].map(([time,text])=>({time,text})))
];

const add=(phaseId,title,tasks)=>{
 const phase=EVENT_PHASES.find(p=>p.id===phaseId),free=phase.categories.findIndex(c=>c.title.includes('Freie Zusatzaufgaben'));
 phase.categories.splice(free<0?phase.categories.length:free,0,c(title,tasks));
};
const meta=(area,due,budgetKey,dependencies,note,planStatus='offen')=>({area,due,budgetKey,dependencies,planStatus,note});

add('phase1','📦 Bestand, Anbieter & Transport',[
 t('toilet_trailer_terms','prio-1','Verfügbarkeit und Lieferbedingungen des Toilettenwagens prüfen',meta('Toilette','2026-10-31','grounds_sanitary',['now_dixie_zustand'],'Notwendige Event-Sanitärlösung.')),
 t('other_ages_terms','prio-1','Mietbedingungen für Bankett-Sets, Weinkrüge, Festzeltgarnituren, Servierschüsseln und Jutedecken dokumentieren',meta('Other Ages','2026-10-31','oa_bankett',['grounds_transport'],'Abholung, Rückgabe, Kaution und Schäden klären.')),
 t('friends_loans','prio-2','Offene Leihgaben im Freundeskreis abfragen',meta('Inventur','2026-10-31','',[],'Nur bestätigte Zusagen als vorhanden markieren.'))
]);
add('phase3','🧾 Reservieren & verbindlich klären',[
 t('reserve_toilet_trailer','prio-1','Toilettenwagen reservieren',meta('Toilette','2027-01-29','grounds_sanitary',['toilet_trailer_terms'],'Lieferung, Standort und Abholung bestätigen.','geplant')),
 t('reserve_other_ages','prio-1','Bankett-Sets, vier Weinkrüge, vier Festzeltgarnituren, zwei Servierschüsseln und vier Jutedecken vorreservieren',meta('Other Ages','2027-01-29','oa_bankett',['other_ages_terms','seating_commit'],'Notwendige Mietpositionen gemeinsam bestätigen; Sitzplatzbedarf vorher festlegen.','geplant')),
 t('confirm_other_ages_transport','prio-1','Selbstabholung und Rückgabe bei Other Ages verbindlich klären',meta('Logistik','2027-01-29','oa_transport',['reserve_other_ages','grounds_transport'],'Bankett-Koffer und Krüge transportsicher einplanen.')),
 t('plan2_erste_hilfe','prio-1','Erste-Hilfe-Kasten prüfen und fehlendes Material beschaffen',meta('Sicherheit','2027-01-29','erstehilfe',['plan2_wetterschutz_inventur'],'Bestehende stabile Aufgabe; gut sichtbar und schnell erreichbar einplanen.')),
 t('plan2_loeschmittel','prio-1','Feuerlöscher, Löschdecken und geeignete Löschmittel beschaffen',meta('Sicherheit','2027-01-29','brandschutz',['plan2_wetterschutz_inventur'],'Bestehende stabile Aufgabe; Feuer- und Kochstellen gemeinsam absichern.')),
 t('decide_jute','prio-2','Miet-Jutedecken bestätigen oder optional Jute-Meterware wählen',meta('Other Ages','2027-01-29','oa_jute',['other_ages_terms'],'Meterware nur statt, nicht zusätzlich zur Mietlösung.'))
]);
add('phase5','🍲 Mengen, Einladungen & Bestellung',[
 t('send_invitations_rsvp','prio-1','Einladungen verschicken und Rückmeldungen sammeln; um Spenden oder Mitgebrachtes bitten, aber nicht als Budgetentlastung rechnen',meta('Gäste','2027-03-29','',[],'Teilnehmerzahl und Zahl der Fleischesser aktualisieren.')),
 t('finalize_stew_recipe','prio-1','Rezept und Mengen für den veganen herzhaften Eintopf im 14-Liter-Kessel festlegen',meta('Essen','2027-03-29','essen_gesamt',['send_invitations_rsvp'],'Kesselvolumen und Portionen prüfen.')),
 t('finalize_grill_supplement','prio-1','Kartoffeln, vegane Würstchen/Alternativen und kleine Fleischmenge für 3–4 Personen festlegen',meta('Essen','2027-03-29','essen_gesamt',['send_invitations_rsvp'],'Fleisch getrennt behandeln.')),
 t('finalize_drink_amounts','prio-1','Mengen für Bier, Wein, abgefülltes Wasser und alkoholfreie Getränke aktualisieren',meta('Getränke','2027-03-29','getraenke_gesamt',['send_invitations_rsvp'],'Separate Versorgung unter dem zweiten Pavillon.')),
 t('test_drink_dispensers','prio-1','Zwei Getränkespender auf Bestand und Funktion prüfen',meta('Alchemistenstation','2027-03-29','alchemie',['plan2_wetterschutz_inventur'],'Je einer für Hibiskus- und Butterfly-Pea-Trank.')),
 t('finalize_potion_ingredients','prio-2','Zutaten und Rezept für Hibiskus- und Butterfly-Pea-Getränke festlegen',meta('Alchemistenstation','2027-03-29','alchemie_zutaten',['test_drink_dispensers'],'Beide Getränke alkoholfrei.')),
 t('add_consumables_to_list','prio-1','Holz-Einwegbesteck, Servietten, Küchenrolle und große Müllbeutel auf die Einkaufsliste setzen',meta('Verbrauchsmaterial','2027-03-29','verbrauchsmaterial',[],'Müllbeutel nur einmal kalkulieren.'))
]);
add('phase6','📦 Einkauf & Packlisten',[
 t('optional_decor_go_no_go','prio-3','Holzwanne, Strohballen und Jute-Meterware nur bei ausreichendem Restbudget freigeben',meta('Optionen','2027-04-24','holzwanne',['apr_mengenplanung'],'Alle drei Positionen bleiben optional und budgetabhängig.','optional')),
 t('prepare_boundaries','prio-1','Pfosten, Befestigungen und Geländeabgrenzungen vorbereiten',meta('Gelände','2027-04-24','pfosten',['plan2_lageplan_final'],'Befestigungsmaterial direkt zuordnen.')),
 t('buy_fire_supplies','prio-1','Feuerholz, Kohle und Anzünder beschaffen',meta('Essen & Feuer','2027-04-24','brennstoff',[],'Trocken lagern.')),
 t('cooling_storage_plan','prio-1','Kühl- und Lagerkonzept mit drei vorhandenen Kühlboxen festlegen',meta('Logistik','2027-04-24','kuehlung',['plan2_wetterschutz_inventur','finalize_drink_amounts'],'Eis/Kühlmaterial bleibt optionale Zusatzposition.')),
 t('organize_water','prio-1','Kanister und abgefülltes Trinkwasser organisieren',meta('Wasser','2027-04-24','wasserlogistik',['plan2_wetterschutz_inventur'],'Quellwasser nur für Reinigung und Handhygiene.'))
]);
const packTask=EVENT_PHASES.flatMap(phase=>phase.categories).flatMap(category=>category.tasks).find(task=>task.id==='may_material_packen');
Object.assign(packTask,{timing:'Spätestens 23. Mai 2027',hint:'Jede Kiste beschriften; Mietmaterial und Rückgabe getrennt kennzeichnen.',sections:[
 {title:'Wetterschutz, Gelände & Deko',items:[['pack_canopy','6×6-m-Baldachin, Pavillon, Abspannungen und Heringe'],['pack_boundary','Pfosten, sichtbare Abgrenzung, Schilder und Befestigungsmaterial'],['pack_decor','Wimpelketten, Banner, acht LED-Laternen und zusätzliche Beleuchtung']]},
 {title:'Küche, Buffet & Geschirr',items:[['pack_cooking','14-Liter-Kessel, Schwenkgrill, Werkzeuge, Feuerholz, Kohle und Anzünder'],['pack_banquet','Fünf Bankett-Koffer, vier Weinkrüge, zwei Servierschüsseln und vier Festzeltgarnituren'],['pack_serving','Akazien-/Holzbretter, Holz-Einwegbesteck und vier Miet-Jutedecken']]},
 {title:'Getränke, Kühlung & Wasser',items:[['pack_alchemy','Zwei Getränkespender, 20 Korkfläschchen und Zutaten für Hibiskus- und Butterfly-Pea-Trank'],['pack_drinks','Bier, Wein, abgefülltes Trinkwasser und weitere alkoholfreie Getränke getrennt packen'],['pack_cooling','Drei vorhandene Kühlboxen, Behälter und nur bei Bedarf Eis/Kühlmaterial'],['pack_water','Kanister für Reinigung und Handhygiene; Quellwasser klar als Nicht-Trinkwasser markieren']]},
 {title:'Sanitär, Sicherheit & Verbrauch',items:[['pack_dixi','Dixi-Reinigungsmaterial, Seife und Desinfektion'],['pack_safety','Feuerlöscher, Löschdecken, Wassereimer und Erste-Hilfe-Material'],['pack_consumables','Servietten, Küchenrolle und große Müllbeutel ohne Doppelposten']]},
 {title:'Optional & Rückgabe',items:[['pack_optional','Holzwanne, Strohballen oder Jute-Meterware nur nach Budgetfreigabe'],['pack_returns','Leere Rückgabekisten, Schutzmaterial, Mietliste und Schadensdokumentation']]}
 ].map(section=>({...section,items:section.items.map(([id,text])=>({id,text}))}))});
add('phase7','🥬 Letzte Woche & Mietabholung',[
 t('pre_cool_drinks','prio-1','Getränke vorkühlen und benötigtes Eis/Kühlmaterial besorgen',meta('Getränke','2027-05-27','kuehlung',['cooling_storage_plan'],'Optionales Kühlmaterial nur nach tatsächlichem Bedarf.')),
 t('prepare_potions','prio-1','Heiltrank- und Manatrank-Zutaten vorbereiten',meta('Alchemistenstation','2027-05-28','alchemie_zutaten',['finalize_potion_ingredients'],'Hibiskus rot, Butterfly Pea blau.')),
 t('collect_other_ages','prio-1','Geschirr, Weinkrüge, Servierschüsseln und Festzeltgarnituren abholen',meta('Other Ages','2027-05-28','oa_transport',['confirm_other_ages_transport'],'Mietmaterial direkt dokumentieren.')),
 t('check_banquet_cases','prio-1','Bankett-Koffer auf Vollständigkeit und Schäden prüfen',meta('Other Ages','2027-05-28','oa_bankett',['collect_other_ages'],'Pro Set 6 Teller, 6 Becher, 6 Suppenschalen und 6 Schnapsbecher.')),
 t('update_setup_map','prio-1','Lage- und Aufbauplan mit allen Stationen aktualisieren',meta('Aufbau','2027-05-26','',['plan2_lageplan_final'],'Getränke- und Alchemistenstation getrennt eintragen.'))
]);
add('phase8','📦 Stationsaufbau & Rückgabe',[
 t('setup_separate_drink_stations','prio-1','Vorhandene Kühlboxen und gegebenenfalls die freigegebene optionale Holzwanne aufbauen; Getränkeversorgung und Alchemistenstation getrennt einrichten',meta('Getränke','2027-05-29','getraenke_gesamt',['cooling_storage_plan'],'Kühlboxen bleiben die eigentliche Kühlung; Alkohol wird nicht der Alchemistenstation zugerechnet.')),
 t('setup_tableware','prio-1','Bankett-Sets, Weinkrüge, Servierschüsseln, Holzbretter und Jutedecken verteilen',meta('Geschirr','2027-05-29','oa_bankett',['check_banquet_cases'],'Keine gemieteten Servierplatten.')),
 t('setup_hygiene_waste','prio-1','Wasser, Seife, Desinfektion, Servietten und Müllbeutel sichtbar bereitstellen',meta('Hygiene','2027-05-29','verbrauchsmaterial',['organize_water'],'Müllmaterial zentral und an Stationen verteilen.')),
 t('return_rentals','prio-1','Geschirr, Mietmaterial und Transport nach dem Fest vollständig kontrollieren und zurückgeben',meta('Rückgabe','2027-05-31','oa_transport',['setup_tableware'],'Schäden und Vollständigkeit vor Rückgabe dokumentieren.'))
]);
const taskBudgetLinks={
 plan2_budgetrahmen:['beschaffungsreserve'],plan2_wetterschutz_inventur:['baldachin_kauf','laternen','kruege'],feb_strombedarf:['stromverteilung'],
 larp_production:['druckmaterial'],entrance_build:['eingangstor'],reserve_other_ages:['oa_bankett','oa_weinkruege','oa_garnituren','oa_servierschuesseln','oa_jute','oa_feuerkoerbe'],
 apr_kuecheninventur:['grillwerkzeug','holzbretter','lagerboxen'],add_consumables_to_list:['verbrauchsmaterial','holzbesteck'],
 prepare_boundaries:['pfosten','reparaturkoffer'],deko_april_production:['banner_wimpel','beschilderung'],
 optional_decor_go_no_go:['holzwanne','stroh','jute_meterware','oa_pranger'],setup_tableware:['oa_bankett','oa_weinkruege','oa_garnituren','oa_servierschuesseln','holzbretter','kruege','oa_jute']
};
EVENT_PHASES.flatMap(phase=>phase.categories).flatMap(category=>category.tasks).forEach(task=>{
 const keys=[task.budgetKey,...(taskBudgetLinks[task.id]||[])].filter(Boolean);
 if(keys.length)task.budgetKeys=[...new Set(keys)];
});
export function replaceEventPlan(target){target.splice(0,target.length,...structuredClone(EVENT_PHASES));}
