// Canonical planning revision. Task state and comments remain in Firebase under stable ids.
const t=(id,prio,text)=>({id,prio,text});
const c=(title,tasks)=>({title,tasks});
const p=(id,title,subtitle,categories,timeline=[])=>({id,label:id==='phase8'?'29. Mai 2027':id.replace('phase','Phase '),title,subtitle,categories:[...categories,c('➕ Freie Zusatzaufgaben',[])],timeline});
export const projectMilestones=[['milestone_site_exposed','31.10.2026','Gelände freigelegt'],['plan2_lageplan_final','28.02.2027','Layout Freeze'],['milestone_concept_freeze','31.03.2027','Konzept Freeze'],['milestone_production_complete','09.05.2027','Production Complete'],['milestone_site_ready','23.05.2027','Site Ready'],['milestone_build_complete','28.05.2027','Build Complete']].map(([id,date,title])=>({id,date,title}));
export const EVENT_PHASES=[
p('phase1','Bestand & Richtung','September 2026',[
 c('🔴 MUSS · Kernplanung',[t('plan2_budgetrahmen','prio-1','5.000 EUR als Obergrenze, nicht als Ausgabenziel, festhalten'),t('plan2_budgetstruktur','prio-1','Budget in bereits ausgegeben, geplant, Reserve und Prognose gliedern'),t('now_dixie_zustand','prio-1','Vorhandenes Dixi für Arbeitseinsätze prüfen; nicht als finale Event-Sanitärlösung voraussetzen'),t('plan2_wetterschutz_inventur','prio-1','Gekauften 6 × 6 m Baldachin und vorhandenen 3 × 6 m Pavillon vollständig prüfen')]),
 c('🟠 SOLL · Deko',[t('deko_sep_bestand','prio-2','Deko-, Licht- und Schilderbestand dokumentieren und Stilrichtung festlegen'),t('deko_sep_prototyp','prio-2','Höchstens eine Musterkombination aus Banner, Wimpel und Stoff testen; keine Großproduktion')])
]),
p('phase2','Gelände freilegen','Oktober 2026',[
 c('🔴 MUSS · Ergebnis',[t('milestone_site_exposed','prio-1','MEILENSTEIN · Gelände freigelegt: Hauptfläche begehbar, zentrale Flächen und Wege offen, Vermessung und Fotos möglich'),t('now_baldachin_lager_transport','prio-1','Transport und trockene Lagerung des bereits gekauften Baldachins klären')])
]),
p('phase3','Auswerten & planen','November 2026 – Januar 2027',[
 c('🔴 MUSS · Grundlayout',[t('layout_basisversorgung','prio-1','Wetterschutz, Sitzplätze, Küche, Sanitär, Hauptwege und Transportflächen im Lageplan anordnen'),t('sanitary_requirements','prio-1','Anforderungen und Anschlüsse der endgültigen Sanitärlösung festhalten')]),
 c('🟠 SOLL · Gestaltung',[t('deko_winter_layout','prio-2','Eingang, Tor, Banner, Wimpel, Licht, Ritual-, Haupt- und Wettkampfbereiche am realen Gelände planen'),t('entrance_measure','prio-2','Eingang nach Freischnitt vermessen und fotografieren; Gestaltung danach festlegen'),t('ritual_location','prio-2','Ritualstandort nur nachrangig im Lageplan bestimmen')]),
 c('🟠 SOLL · Hybrid-LARP',[t('larp_rules_freeze','prio-2','Regeln für 30 Schicksalskarten, Sidequests, Hauptquest, Silberlinge, Questmeister und Auktion einfrieren; keine Kernmechanik ergänzen'),t('larp_design_freeze','prio-2','Karten- und Questzettel-Layout finalisieren')])
]),
p('phase4','Layout Freeze & Beschaffung','Februar – März 2027',[
 c('🔴 MUSS · Infrastruktur',[t('plan2_lageplan_final','prio-1','MEILENSTEIN · Layout bis 28.02. für Wetterschutz, Sitzplätze, Küche, Sanitär, Eingang, Wettkämpfe, Quest, Ritual und Wege festlegen'),t('feb_strombedarf','prio-1','Strombedarf, Beleuchtung, Kabel und sichere Kabelwege bestimmen'),t('seating_commit','prio-1','Bierzeltgarnituren beziehungsweise ausreichende Sitzplätze verbindlich organisieren'),t('plan2_helferrollen','prio-1','Rollen vergeben: Aufbau, Küche, Getränke, Wettkampf, Abbau, Logistik, Questmeister, Herold, Abendtechnik und optional Ritualleitung')]),
 c('🔴 MUSS · Versorgung',[t('plan2_essenskonzept','prio-1','Finales Speise- und Getränkekonzept einschließlich Trinkwasser und Kühlung festhalten'),t('kitchen_core_plan','prio-1','Kochstellen, Grill, Kessel/Topf, Arbeitsflächen, Geschirr und Serviermaterial planen')]),
 c('🟠 SOLL · Produktionsstart',[t('deko_material_plan','prio-2','Nach finalem Geländeplan Mengen für Stoff, Holz/Pfosten und Befestigung sowie Produktionsliste bestimmen'),t('entrance_design','prio-2','Torbauweise, Verankerung und modulare Transportkonstruktion planen'),t('larp_production','prio-2','Schicksalskarten, Sidequests, Silberlinge und notwendige Questobjekte produzieren'),t('music_scope','prio-2','Tatsächlich genutzte Liveinstrumente festlegen; zusätzliche Instrumente bleiben optional')]),
 c('🔴 MUSS · Freeze',[t('milestone_concept_freeze','prio-1','MEILENSTEIN · Konzept Freeze 31.03.: keine neuen großen Attraktionen, Mechaniken oder Bauprojekte')]),
 c('🟢 BONUS',[t('clay_oven_go_no_go','prio-3','Anfang April Lehmofen nur bei Zeit, Helfern, Material und Trocknungswetter freigeben; sonst streichen')])
]),
p('phase5','Produzieren & testen','April 2027',[
 c('🔴 MUSS · Infrastruktur',[t('apr_planen_testaufbau','prio-1','Baldachin und Pavillon vollständig probeaufbauen, abspannen und prüfen'),t('apr_transportprobe','prio-1','Transport, Packlogik und Aufbaufolge testen'),t('plan2_erste_hilfe','prio-1','Erste-Hilfe-Ausstattung prüfen und ergänzen'),t('plan2_loeschmittel','prio-1','Geeignete Löschmittel organisieren'),t('waste_transport_plan','prio-1','Müllentsorgung, Fahrzeuge, Materialtransport sowie Auf- und Abbauhelfer planen')]),
 c('🔴 MUSS · Versorgung',[t('apr_mengenplanung','prio-1','Mengen für Essen, Getränke, Trinkwasser und Reserve planen'),t('apr_kuecheninventur','prio-1','Kühlung, Kochstellen, Grill, Kessel, Arbeitsflächen, Geschirr und Serviermaterial prüfen'),t('plan2_prep_zeitplan','prio-1','Vorbereitungsplan für Vortag und Eventtag erstellen')]),
 c('🟠 SOLL · Produktion & Test',[t('entrance_build','prio-2','Modulares Tor bis Ende April bauen und probeaufbauen'),t('deko_april_production','prio-2','Banner, Wimpel, Schilder und nötige Deko montagefertig herstellen'),t('larp_full_test','prio-2','LARP mit mehreren Personen testen: Hauptquest, Questökonomie und problematische Aufgaben überarbeiten'),t('event_dramaturgy','prio-2','Dramaturgie aus Wettkämpfen, Karten, Quests, Essen, Siegerehrung, Ritual/Auktion und Abendprogramm zusammenführen'),t('music_tech_test','prio-2','PA, Licht, ausgewählte Liveelemente und Technikposition testen')]),
 c('🟢 BONUS · Ritual & Effekte',[t('ritual_project','prio-3','Ritualplatz: Standort, drei Monolithen und Altar festlegen, Materialtest machen, bauen und Stand-/Wetterfestigkeit prüfen'),t('fog_test','prio-3','Nebelmaschine nur bei sicherer, tatsächlich geplanter Nutzung testen')])
]),
p('phase6','Production Complete & Site Ready','1.–23. Mai 2027',[
 c('🔴 MUSS · Abschluss',[t('milestone_production_complete','prio-1','MEILENSTEIN · Production Complete ca. 09.05.: Eigenbauten und LARP-Material montagefertig'),t('plan2_finale_einkaufsliste','prio-1','Finale Liste für Essen, Getränke, Verbrauchsmaterial und Kerninfrastruktur'),t('may_material_packen','prio-1','Material nach Bereichen packen und Fahrzeugen zuordnen')]),
 c('🔴 MUSS · Gelände',[t('plan2_rampe_sichern','prio-1','Stolperstellen und größere Gefahren beseitigen; Wege und Rampe sichern'),t('milestone_site_ready','prio-1','MEILENSTEIN · Site Ready ca. 23.05.: Schnitt, Wege, Flächen und Sicherheitskontrolle fertig')]),
 c('🔴 MUSS · Versorgung',[t('may_helfer_bestaetigen','prio-1','Kernrollen und Ankunftszeiten bestätigen; eine Person darf mehrere Rollen übernehmen'),t('plan2_lebensmittel_einkauf','prio-1','Lebensmittel gestaffelt beschaffen und Kühlkette sichern'),t('plan2_getraenke_einkauf','prio-1','Getränke und Trinkwasserreserve beschaffen'),t('sanitary_delivery_check','prio-1','Sanitär-Lieferung, Abholung, Licht, Material und Handwaschen bestätigen')]),
 c('🟠 SOLL · Programm packen',[t('larp_event_pack','prio-2','Questmeister-Unterlagen, Questbrett, Regeln, Hauptquest, Auktionspreise und Kartenwahl fertigstellen und packen'),t('music_pack','prio-2','Technik packen, Kabel/Strom zuordnen und verantwortliche Person benennen'),t('ritual_pack','prio-3','Ritualelemente nur falls umgesetzt transportfest verpacken')])
]),
p('phase7','Aufbau – keine Produktion','27.–28. Mai 2027',[
 c('🔴 MUSS · Donnerstag 27.05. Schweraufbau',[t('plan2_wetterschutz_aufbauen','prio-1','Baldachin und Pavillon aufstellen, abspannen und Sitzplätze einrichten'),t('heavy_build_logistics','prio-1','Garnituren, Mietmaterial, Küche, Tor und große Konstruktionen aufbauen'),t('plan2_strom_verlegen','prio-1','Grundstrom verlegen und Kabelwege sichern'),t('plan2_kueche_aufbauen','prio-1','Küche mit Kühlung, Kochstellen, Grill, Kessel, Flächen und Wasser aufbauen')]),
 c('🔴 MUSS · Freitag 28.05. Feinaufbau',[t('plan2_sicherheitscheck_aufbau','prio-1','Sanitär, Wege, Kabel, Licht, Erste Hilfe und Löschmittel final prüfen'),t('milestone_build_complete','prio-1','MEILENSTEIN · Build Complete 28.05.: alles steht; Eventtag ohne Bauarbeiten')]),
 c('🟠 SOLL · Freitag Atmosphäre',[t('entrance_event_build','prio-2','Vorgefertigtes Tor am 27./28. Mai aufbauen und verankern'),t('plan2_deko_aufhaengen','prio-2','Vorgefertigte Banner, Wimpel, Schilder, Licht und Deko montieren'),t('quest_area_build','prio-2','Questbereich mit fertig gepacktem Material aufbauen'),t('ritual_event_build','prio-3','Ritualplatz nur falls fertig vor Ort montieren'),t('music_event_build','prio-2','Abendtechnik aufstellen und prüfen')]),
 c('🔴 MUSS · Küche Vorabend',[t('plan2_grill_marinieren','prio-1','Lebensmittel vorbereiten, portionieren und kühlen'),t('plan2_kessel_vorbereiten','prio-1','Kesselgericht und zeitkritische Küchenarbeiten vorbereiten')])
]),
p('phase8','Eventtag & Abbau','Nur Versorgung, Restpunkte und Veranstaltung',[
 c('🔴 MUSS · Eventtag',[t('event_no_build','prio-1','Keine Banner, Monolithen oder Tore bauen; nur Versorgung, Küchenarbeiten und kleine Restpunkte'),t('plan2_event_strom','prio-1','Strom, Kabelwege und Licht funktionieren'),t('plan2_trinkwasser','prio-1','Trinkwasser sichtbar bereitstellen'),t('plan2_event_dixie','prio-1','Finale Sanitärlösung ist erreichbar, beleuchtet, ausgestattet und hat Handwaschen'),t('plan2_event_erstehilfe','prio-1','Erste Hilfe und Verantwortung sind geklärt'),t('plan2_event_loeschmittel','prio-1','Löschmittel stehen an Feuer- und Kochstellen'),t('plan2_event_aufsicht','prio-1','Waffenwettkämpfe nur nüchtern, beaufsichtigt und abgesichert')]),
 c('🟠 SOLL · Programm',[t('plan2_event_punkteliste','prio-2','Wettkampfwertung und Moderation durchführen'),t('plan2_event_musik','prio-2','Musik und Abendatmosphäre betreuen'),t('larp_event_run','prio-2','Karten, Sidequests, Hauptquest, Silberlinge und Auktion mit Questmeister durchführen')]),
 c('🔴 MUSS · Abbau',[t('plan2_abbau_muell','prio-1','Müll vollständig entfernen'),t('plan2_abbau_material','prio-1','Wetterschutz, Möbel, Küche, Technik und Material trocken verstauen'),t('plan2_abbau_endkontrolle','prio-1','Gelände auf Heringe, Kabel, Werkzeuge, Gefahren und Müll kontrollieren')])
],[['12:00','Ankunft'],['14:00–16:00','Wettkämpfe'],['16:00–17:30','Essen'],['17:30–19:00','Weitere Wettbewerbe und Questfinale'],['19:00–20:00','Siegerehrung, Ritual/Auktion'],['ab 20:00','Tavernenabend']].map(([time,text])=>({time,text})))
];
export function replaceEventPlan(target){target.splice(0,target.length,...structuredClone(EVENT_PHASES));}
