import {FOOD_TASKS,FOOD_DECISIONS,FOOD_EQUIPMENT} from './food-plan.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=items=>`<ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const fmt=n=>Number(n||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
let store={},save=()=>{},tasks={},budget={};
export function initFood(container,app,onSave){save=onSave;const view=document.createElement('section');view.id='foodView';view.dataset.view='food';view.className='orga-view food-view';container.append(view);renderFood();}
export function updateFood(value,taskState,budgetState){store=value||{};tasks=taskState||{};budget=budgetState||{};renderFood();}
function renderFood(){const el=document.getElementById('foodView');if(!el)return;
 const decisions=store.decisions||{},gear=store.equipment||{};
 const costs=[['Lebensmittel','essen_gesamt','220–250 €',235],['Getränke · Hypocras','food_drinks','30–50 €',40],['Küchenequipment','food_tools','Plananteil',45],['Verbrauchsmaterial','food_consumables','Plananteil',20],['Mietmaterial','oa_servierschuesseln','bei Bedarf',0]];
 el.innerHTML=`<div class="codex-page-heading"><p class="folio-label">Interne Organisation / Verpflegung</p><h2>Verpflegungskonzept</h2><p>Vom Markt zum Wintermahl · vollständig vegan · 29.05.2027</p></div>
 <div class="food-status"><strong>Status: Konzept festgelegt</strong><span>ca. 25 Personen</span><span>Ein warmes Hauptgericht</span><span>Gesamtziel Verpflegung: ca. 300–380 € · Planwerte</span></div>
 <div class="food-grid"><article><h3>1 · Markttafel</h3><p>Ankunft bis Nachmittag · ohne festen Essenszeitpunkt, während Spielen und Quest.</p>${list(['Sauerteigbrot','2–3 rustikale vegane Aufstriche','Eingelegtes Gemüse','Äpfel und Birnen','Nüsse und Trockenfrüchte','ca. 36 kleine herzhafte Pasteten'])}<p>Portionsweise nachlegen; empfindliche Ware geschützt und gekühlt halten.</p></article><article><h3>2 · Wintermahl</h3><p><strong>Schmortopf des Dreißigsten Winters</strong> · ca. 10 Liter fertig, ca. 400 ml pro Person.</p>${list(['Seitan, braune oder grüne Linsen, Champignons','Zwiebeln, Möhren, Pastinaken oder Rüben','Trockenpflaumen, wenige Rosinen','Gemüsebrühe, Senf, Essig, Pfeffer, Ingwer','Wenig Zimt und Nelke'])}<p>Dazu Sauerteigbrot, Pickles und 2–3 Saucen: Senf, Kräuter, optional Apfel-Pfeffer. Kein zweites warmes Hauptgericht.</p></article><article><h3>3 · Später Abend</h3>${list(['Gyngerbrede / dunkles Gewürzbrot','Obst, Nüsse und Trockenfrüchte','Hypocras','Alkoholfreie Gewürzalternative'])}<p>Keine warme Dessertproduktion.</p></article></div>
 <article class="food-panel"><h3>Produktionsprinzip</h3><strong>Zu Hause produzieren, vor Ort nur regenerieren und ausgeben.</strong><ol>${['Schmortopf vollständig zu Hause vorkochen','In mehrere kleine, flache Lebensmittelbehälter füllen','Schnell herunterkühlen und gekühlt lagern','In Kühlboxen transportieren','Vor Ort in den Potjie geben','Über Feuer und Glut vollständig erhitzen','Mit Einstichthermometer kontrollieren','Bis zur Ausgabe heiß halten','Direkt aus dem Potjie servieren'].map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p>Vorhandener Potjie: 14 l Nennvolumen, Ziel 10 l, sinnvoll höchstens 10–11 l. Brot, Pasteten und Beilagen ergänzen die Sättigung. Kein 30-l-Kessel, Chafing Dish, Hockerkocher, zusätzliche Gasflasche oder mobile Gastro-Küche beschaffen.</p></article>
 <article class="food-panel"><h3>Equipment · vorhanden / benötigt / Status</h3><div class="food-table-wrap"><table><thead><tr><th>Gegenstand</th><th>Bedarf</th><th>Status</th><th>Menge</th><th>Kaufen / leihen / vorhanden</th><th>Kosten €</th><th>Bezugsquelle</th><th>Verantwortlich</th><th>Spätestens</th></tr></thead><tbody>${FOOD_EQUIPMENT.map(([name,kind],i)=>{const g=gear[i]||{};const input=(field,type='text')=>`<input aria-label="${esc(name)}: ${field}" type="${type}" value="${esc(g[field]??(field==='cost'&&kind==='Vorhanden'?0:''))}" data-food-gear="${i}" data-field="${field}">`;return `<tr><th>${esc(name)}</th><td>${esc(kind)}</td><td><select data-food-gear="${i}" data-field="status">${['Offen','Prüfen','Reserviert','Bestellt','Vorhanden','Erledigt'].map(s=>`<option ${s===(g.status|| (kind==='Vorhanden'?'Vorhanden':'Offen'))?'selected':''}>${s}</option>`).join('')}</select></td><td>${input('quantity')}</td><td><select data-food-gear="${i}" data-field="sourceType">${['Prüfen','Kaufen','Leihen','Vorhanden'].map(s=>`<option ${s===(g.sourceType||(kind==='Vorhanden'?'Vorhanden':'Prüfen'))?'selected':''}>${s}</option>`).join('')}</select></td><td>${input('cost','number')}</td><td>${input('source')}</td><td>${input('responsible')}</td><td>${input('due','date')}</td></tr>`}).join('')}</tbody></table></div></article>
 <article class="food-panel"><h3>Produktions- und Beschaffungszeitplan</h3><p>Alle Termine sind mit der zentralen Aufgabenliste verknüpft. Status und Verantwortliche werden dort gepflegt.</p><div class="food-timeline">${FOOD_TASKS.map(t=>{const s=tasks[t.id]||{};return `<button data-go="tasks" data-record="${t.id}"><time>${esc(t.due)}</time><span><strong>${esc(t.subcategory)}</strong> · ${esc(t.text)}</span><small>${s.done||s.status==='done'?'Erledigt':esc(s.status||'Offen')}${s.responsible?' · '+esc(s.responsible):''}</small></button>`}).join('')}</div></article>
 <article class="food-panel"><h3>Noch zu entscheiden</h3><div class="food-decisions">${FOOD_DECISIONS.map((d,i)=>{const v=decisions[i]||{};if(v.decided)return "";return `<label class="food-decision"><input type="checkbox" data-food-decision="${i}" ${v.decided?'checked':''}><span>${esc(d)}</span><input type="text" data-food-answer="${i}" value="${esc(v.answer||'')}" placeholder="Festgelegter Plan / Entscheidung"></label>`}).join('')}</div><p>Entschiedene Punkte erscheinen im festgelegten Plan darunter.</p><ul>${FOOD_DECISIONS.map((d,i)=>decisions[i]?.decided?`<li><strong>${esc(d)}:</strong> ${esc(decisions[i].answer||'Festgelegt')} <button type="button" data-food-undecide="${i}">Wieder öffnen</button></li>`:'').join('')}</ul></article>
 <article class="food-panel"><h3>Kosten · Planwerte</h3><p>Lebensmittel 220–250 € · besondere Getränke 30–50 € · zusätzliches Küchenequipment und Verbrauch 35–85 € · Gesamtziel ca. 300–380 €. Vorhandenes Equipment: 0 € Restkosten.</p><div class="food-table-wrap"><table><thead><tr><th>Kategorie</th><th>Plan</th><th>Bereits ausgegeben</th><th>Noch offen</th><th>Abweichung zum Plan</th></tr></thead><tbody>${costs.map(([label,key,range,fallback])=>{const b=budget['plan_'+key]||{};const p=Number(b.planned??fallback),a=Number(b.actual||0);return `<tr><th>${esc(label)}</th><td>${esc(range)} (${fmt(p)})</td><td>${fmt(a)}</td><td>${fmt(Math.max(0,p-a))}</td><td>${fmt(a-p)}</td></tr>`}).join('')}</tbody></table></div><p><button data-go="budget">Budget und Ist-Ausgaben bearbeiten ↗</button></p></article>
 <article class="food-panel"><h3>Verantwortlichkeiten und offene Aufgaben</h3><p>Personen bei den einzelnen Aufgaben oder Equipmentposten eintragen. Küchenverantwortliche Person bis Anfang Mai festlegen.</p>${FOOD_TASKS.filter(t=>!tasks[t.id]?.done&&tasks[t.id]?.status!=='done').slice(0,8).map(t=>`<button class="food-task-link" data-go="tasks" data-record="${t.id}">${esc(t.due)} · ${esc(t.text)} ↗</button>`).join('')}</article>`;
 el.querySelectorAll('[data-food-gear]').forEach(input=>input.addEventListener('change',()=>save(`equipment/${input.dataset.foodGear}/${input.dataset.field}`,input.value)));
 el.querySelectorAll('[data-food-decision]').forEach(input=>input.addEventListener('change',()=>save(`decisions/${input.dataset.foodDecision}/decided`,input.checked)));
 el.querySelectorAll('[data-food-undecide]').forEach(input=>input.addEventListener('click',()=>save(`decisions/${input.dataset.foodUndecide}/decided`,false)));
 el.querySelectorAll('[data-food-answer]').forEach(input=>input.addEventListener('change',()=>save(`decisions/${input.dataset.foodAnswer}/answer`,input.value)));
}


